version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: forgiveness-db
    restart: always
    environment:
      POSTGRES_DB: forgiveness_journey
      POSTGRES_USER: forgiveness_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - forgiveness-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forgiveness_user -d forgiveness_journey"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: forgiveness-backend
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://forgiveness_user:${DB_PASSWORD:-secure_password_123}@database:5432/forgiveness_journey
      SESSION_SECRET: ${SESSION_SECRET:-your_session_secret_here_make_it_long_and_random}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      REPLIT_DOMAINS: ${DOMAIN:-forgiveness.info}
      ISSUER_URL: https://replit.com/oidc
      REPL_ID: ${REPL_ID:-your_repl_id}
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - forgiveness-network
    volumes:
      - ./server:/app/server:ro
      - ./shared:/app/shared:ro
      - ./node_modules:/app/node_modules:ro

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: forgiveness-frontend
    restart: always
    environment:
      VITE_API_URL: http://backend:5000
      VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - forgiveness-network
# Remove this volume mount - using built-in files

  nginx:
    image: nginx:alpine
    container_name: forgiveness-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - forgiveness-network

volumes:
  postgres_data:
    driver: local

networks:
  forgiveness-network:
    driver: bridge