services:
  database:
    image: postgres:15-alpine
    container_name: forgiveness-db
    restart: always
    environment:
      POSTGRES_DB: forgiveness_journey
      POSTGRES_USER: forgiveness_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - forgiveness-network
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U forgiveness_user -d forgiveness_journey"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:

networks:
  forgiveness-network:
    driver: bridge
